### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by vaibhavjnf** [SahilChachra/Video-Analytics-Dashboard#9]
![error 1](https://user-images.githubusercontent.com/15798711/187697548-0f5ce232-91e0-409e-82b9-1648de5ec8d9.PNG)
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\intel\Desktop\Video-Analytics-Dashboard-main>  streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.29.114:8501

2022-08-31 18:58:38.650 Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Folder exists, overwriting...
2022-08-31 18:58:38.674 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 18:58:38.686 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 18:58:38.792 Fusing layers...
2022-08-31 18:58:39.092 Model Summary: 213 layers, 7225885 parameters, 0 gradients
2022-08-31 18:58:39.093 WARNING: --img-size (640, 640) must be multiple of max stride 32, updating to [640, 640]
2022-08-31 18:58:39.598 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 232, in <module>
    main()
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 97, in main
    detect(source=video.name, stframe=stframe, kpi1_text=kpi1_text, kpi2_text=kpi2_text, kpi3_text=kpi3_text, js1_text=js1_text, js2_text=js2_text, js3_text=js3_text, conf_thres=float(conf_thres), nosave=nosave, display_labels=display_labels, conf_thres_drift = float(conf_thres_drift), save_poor_frame__= save_poor_frame__, inf_ov_1_text=inf_ov_1_text, inf_ov_2_text=inf_ov_2_text, inf_ov_3_text=inf_ov_3_text, inf_ov_4_text=inf_ov_4_text, fps_warn=fps_warn, fps_drop_warn_thresh  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\deep_list.py", line 170, in detect
    pred = model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\yolov5\models\common.py", line 402, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
  Stopping...
PS C:\Users\intel\Desktop\Video-Analytics-Dashboard-main>  streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.29.114:8501

2022-08-31 19:01:35.927 Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Folder exists, overwriting...
2022-08-31 19:01:35.949 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:01:35.962 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:01:36.090 Fusing layers...
2022-08-31 19:01:36.410 Model Summary: 213 layers, 7225885 parameters, 0 gradients
2022-08-31 19:01:36.412 WARNING: --img-size (640, 640) must be multiple of max stride 32, updating to [640, 640]
2022-08-31 19:01:36.500 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 232, in <module>
    main()
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 162, in main
    detect(source='1', stframe=stframe, kpi1_text=kpi1_text, kpi2_text=kpi2_text, kpi3_text=kpi3_text, js1_text=js1_text, js2_text=js2_text, js3_text=js3_text, conf_thres=float(conf_thres), nosave=nosave, display_labels=display_labels, conf_thres_drift = float(conf_thres_drift), save_poor_frame__= save_poor_frame__, inf_ov_1_text=inf_ov_1_text, inf_ov_2_text=inf_ov_2_text, inf_ov_3_text=inf_ov_3_text, inf_ov_4_text=inf_ov_4_text, fps_warn=fps_warn, fps_drop_warn_thresh = float(fps_drop_warn_thresh))
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\deep_list.py", line 136, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\yolov5\utils\datasets.py", line 309, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 1... Failed to open 1
2022-08-31 19:08:09.912 Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Folder exists, overwriting...
2022-08-31 19:08:09.946 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:08:09.964 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:08:10.071 Fusing layers...
2022-08-31 19:08:10.591 Model Summary: 213 layers, 7225885 parameters, 0 gradients
2022-08-31 19:08:10.594 WARNING: --img-size (640, 640) must be multiple of max stride 32, updating to [640, 640]
2022-08-31 19:08:11.045 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 232, in <module>
    main()
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 97, in main
    detect(source=video.name, stframe=stframe, kpi1_text=kpi1_text, kpi2_text=kpi2_text, kpi3_text=kpi3_text, js1_text=js1_text, js2_text=js2_text, js3_text=js3_text, conf_thres=float(conf_thres), nosave=nosave, display_labels=display_labels, conf_thres_drift = float(conf_thres_drift), save_poor_frame__= save_poor_frame__, inf_ov_1_text=inf_ov_1_text, inf_ov_2_text=inf_ov_2_text, inf_ov_3_text=inf_ov_3_text, inf_ov_4_text=inf_ov_4_text, fps_warn=fps_warn, fps_drop_warn_thresh = float(fps_drop_warn_thresh))
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\deep_list.py", line 170, in detect
    pred = model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\yolov5\models\common.py", line 402, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
2022-08-31 19:12:05.900 Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Folder exists, overwriting...
2022-08-31 19:12:05.940 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:12:05.970 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:12:06.074 Fusing layers...
2022-08-31 19:12:06.440 Model Summary: 213 layers, 7225885 parameters, 0 gradients
2022-08-31 19:12:06.444 WARNING: --img-size (640, 640) must be multiple of max stride 32, updating to [640, 640]
2022-08-31 19:13:37.880 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 232, in <module>
    main()
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 226, in main
    detect(source=rtsp_input, stframe=stframe, kpi1_text=kpi1_text, kpi2_text=kpi2_text, kpi3_text=kpi3_text, js1_text=js1_text, js2_text=js2_text, js3_text=js3_text, conf_thres=float(conf_thres), nosave=nosave, display_labels=display_labels, conf_thres_drift = float(conf_thres_drift), save_poor_frame__= save_poor_frame__, inf_ov_1_text=inf_ov_1_text, inf_ov_2_text=inf_ov_2_text, inf_ov_3_text=inf_ov_3_text, inf_ov_4_text=inf_ov_4_text, fps_warn=fps_warn, fps_drop_warn_thresh = float(fps_drop_warn_thresh))
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\deep_list.py", line 136, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\yolov5\utils\datasets.py", line 309, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: rtsp://192.168.0.1... Failed to open rtsp://192.168.0.1
2022-08-31 19:13:43.080 Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Folder exists, overwriting...
2022-08-31 19:13:43.109 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:13:43.122 YOLOv5  2022-8-4 torch 1.12.1+cpu CPU

2022-08-31 19:13:43.233 Fusing layers...
2022-08-31 19:13:43.638 Model Summary: 213 layers, 7225885 parameters, 0 gradients
2022-08-31 19:13:43.640 WARNING: --img-size (640, 640) must be multiple of max stride 32, updating to [640, 640]
2022-08-31 19:13:44.094 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 232, in <module>
    main()
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\app.py", line 97, in main
    detect(source=video.name, stframe=stframe, kpi1_text=kpi1_text, kpi2_text=kpi2_text, kpi3_text=kpi3_text, js1_text=js1_text, js2_text=js2_text, js3_text=js3_text, conf_thres=float(conf_thres), nosave=nosave, display_labels=display_labels, conf_thres_drift = float(conf_thres_drift), save_poor_frame__= save_poor_frame__, inf_ov_1_text=inf_ov_1_text, inf_ov_2_text=inf_ov_2_text, inf_ov_3_text=inf_ov_3_text, inf_ov_4_text=inf_ov_4_text, fps_warn=fps_warn, fps_drop_warn_thresh = float(fps_drop_warn_thresh))
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\deep_list.py", line 170, in detect
    pred = model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\yolov5\models\common.py", line 402, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\intel\Desktop\Video-Analytics-Dashboard-main\./yolov5\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "C:\Users\intel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by SahilChachra** [comment]
Check the YoloV5 weight file. You are probably using some other versions of weight file. Download and try weights of Yolov5 v6.0 and v6.1

To know which Yolov5 version is being used, go inside Yolov5 folder in this repo, run detect.py with given weight file. Once you run detect.py, the code automatically prints the version.

**Comment by SahilChachra** [comment]
Closing this issue due to inactivity. Please reopen if not resolved.

**Comment by spinxi** [comment]
Check [this](https://github.com/SahilChachra/Video-Analytics-Dashboard/issues/14)
